### ISSUE TITLE
solrcloud6

### ISSUE THREAD

**Issue by solo30years** [liang68/ik-analyzer-solr6#1]
支持solr单机动态词库吗？现在报了空指针

**Comment by liang68** [comment]
solr 单机？不太了解你当前的部署情况。这个代码和是否有几台服务器没有关系，只要你可以成功部署一个集群，将我博客上写的那些配置上传到对应的配置文件中即可。你可以粘贴处具体报错内容看看

**Comment by solo30years** [comment]
D:\solr_cloud\solr-6.6.0\bin>org.apache.solr.core.SolrResourceNotFoundException: Can't find resource 'ik.conf' in classpath or 'D:\solr_cloud\solr-6.6.0\server\solr\gemini'
        at org.apache.solr.core.SolrResourceLoader.openResource(SolrResourceLoader.java:406)
        at org.wltea.analyzer.lucene.IKTokenizerFactory.canUpdate(IKTokenizerFactory.java:99)
        at org.wltea.analyzer.lucene.IKTokenizerFactory.update(IKTokenizerFactory.java:71)
        at org.wltea.analyzer.lucene.UpdateKeeper.run(UpdateKeeper.java:51)
        at java.lang.Thread.run(Thread.java:745)
IK parsing conf NullPointerException~~~~~[Ljava.lang.StackTraceElement;@4538117a

**Comment by solo30years** [comment]
ik.conf这个指的是IKAnalyzer.cfg这个吗

**Comment by liang68** [comment]
哦哦，我知道你哪里有问题了。ik.conf 不是 IKAnalyzer.cfg ， ik.conf 主要用于标识 IK 词库是否有进行更新的，有一个实时扫描程序在扫描这个文件里的内容从而判定是否需要重新加载词库。ik.conf 内容为：
lastupdate=1
files=dict1.txt
其中：lastupdate 后面的数字来记录当前更新版本，如果有需要修改只需要修改这个值重新上传即可。而 files 后面的文件指向你自己的扩展词库，这样你想增加新词库的话，后面用逗号跟着新文件就可以接入新词库文件，而不需要修改 solr ik 底层核心配置文件 IKAnalyzer.cfg，如果修改这个文件必须得重启 solr，这个线上肯定是不允许的（你要知道一个文件大小限制是1MB，所以可能会随着词库的增加，文件数也是需要增加的）
可能我的博客写的不是太清楚，我再更新一下

**Comment by liang68** [comment]
我已经在博客中更新了有关内容，你可以再上去看一下，看看能不能解决你的问题

**Comment by solo30years** [comment]
好的，我再想想看看你的源码。谢谢

**Comment by solo30years** [comment]
您好，“ 7. 新增加IKTokenizerFactoryRemote类，如果想要使用这种方式自动加载词库，那么在solrconfig.xml文件中需要配置这个类即可”。这段话是什么意思，需要再solrconfig.xml中哪里配置？

**Comment by liang68** [comment]
你需要确定一点，我在博客中写到的是两种方案。第一种方案就是你一开始问的问题；第二种方案是读取远程文件或数据库来进行实时更新。我建议你先把第一种方案整完了之后再来搞第二种。
先回答一下你这个问题，因为你新增加了一个类用于读取远程配置，那么如何让 solr 知道你要从哪里读取扩展词库，肯定是需要在其 核心配置文件中配置好的，你将第一种方案中的：
\<tokenizer class="org.wltea.analyzer.lucene.IKTokenizerFactory" useSmart="false" conf="ik.conf"/>
修改为第二种方案新增加那个类就可以了：
\<tokenizer class="org.wltea.analyzer.lucene.IKTokenizerFactoryRemote" useSmart="false" conf="ik.conf"/>

**Comment by solo30years** [comment]
第一种已经完成了。现在尝试第二种，你回答的方案中什么都没有啊？？？

**Comment by solo30years** [comment]
这下明白了。博客中是solrconfig.xml文件中配置。
谢谢

**Comment by fanpeng1100** [comment]
方便加下QQ吗，343405399.还是有些solr问题想请教

**Comment by fanpeng1100** [comment]
111
