### ISSUE TITLE
solr6.6.0版本 配置了无分词的效果

### ISSUE THREAD

**Issue by inotgaoshou** [liang68/ik-analyzer-solr6#3]
solr6.6.0版本 配置了无分词的效果

**Comment by liang68** [comment]
有报什么错误或者你写的日志有没有打印出来等！因为据反映6.4.x 都是可以的，6.6.0我感觉不应该有问题，除非底层有了大的升级

**Comment by inotgaoshou** [comment]
就是配置分词后，没效果了。不过我是单机版配置的，切换其他的分词版本就可以。

**Comment by inotgaoshou** [comment]
我的配置：
solrconfig.xml,
`<lib dir="${solr.install.dir:../../../..}/dist/" regex="ik-analyzer-solr-\d.*\.jar" />`

managed-schema
`<fieldType name="text_ik" class="solr.TextField">   
  <analyzer type="index">
    <tokenizer class="org.wltea.analyzer.lucene.IKTokenizerFactory" useSmart="false" conf="ik.conf" />
    <filter class="solr.StopFilterFactory" ignoreCase="true" words="stopwords.txt" />
  </analyzer>
  <analyzer type="query">
    <tokenizer class="org.wltea.analyzer.lucene.IKTokenizerFactory" useSmart="true" conf="ik.conf" />
    <filter class="solr.StopFilterFactory" ignoreCase="true" words="stopwords.txt" />
  </analyzer>
</fieldType>
`
同目录下添加： ik.conf文件

　2. 往 zk 上传一个集群所需要的配置信息列表 这一步没做。不知单机的模式需要配置吗？

**Comment by liang68** [comment]
和是否是单机没有关系，只要你想要创建一个集群就需要上传对应的要创建集群的配置文件，还会有一个很重要的点就是，类似于："../../../"这一类的一定要查看相对于你当前环境的路径是否正确。
你没有上传这个文件代表 solr 无法依赖你对应的 ik 分词包，没有依赖包它肯定不会给你做任何分词的

**Comment by inotgaoshou** [comment]
谢谢作者的答复，发现问题了，报了这个错：org.apache.solr.core.SolrResourceNotFoundException: Can't find resource 'dict1.txt' ，请问这个dict1.txt里面的内容要写什么，具体的分词字典？有没累死的例子参考，谢谢。我创建了那个dict1.txt，没报错了，但分词还是不对，输入中华人民共和国，没分词

**Comment by liang68** [comment]
这个是你的扩展词库，基本词库有20多万，如果有你自己特殊的词就需要加入到这里，你可以参看我的博客，这块应该有说明的

**Comment by inotgaoshou** [comment]
好的，楼主你的博客我会好好拜读，现在没报错，我在分词那里输入：输入中华人民共和国，显示的结果是


IKT | textraw_bytesstartendpositionLengthtypeposition | textraw_bytesstartendpositionLengthtypeposition | text | raw_bytes | start | end | positionLength | type | position | 中[e4 b8 ad]011CN_CHAR1 | 中[e4 b8 ad]011CN_CHAR1 | 中 | [e4 b8 ad] | 0 | 1 | 1 | CN_CHAR | 1 | 华[e5 8d 8e]121CN_CHAR2 | 华[e5 8d 8e]121CN_CHAR2 | 华 | [e5 8d 8e] | 1 | 2 | 1 | CN_CHAR | 2 | 人[e4 ba ba]231CN_CHAR3 | 人[e4 ba ba]231CN_CHAR3 | 人 | [e4 ba ba] | 2 | 3 | 1 | CN_CHAR | 3 | 民[e6 b0 91]341CN_CHAR4 | 民[e6 b0 91]341CN_CHAR4 | 民 | [e6 b0 91] | 3 | 4 | 1 | CN_CHAR | 4 | 国 | 国 | 国
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
textraw_bytesstartendpositionLengthtypeposition | text | raw_bytes | start | end | positionLength | type | position
text
raw_bytes
start
end
positionLength
type
position
中[e4 b8 ad]011CN_CHAR1 | 中 | [e4 b8 ad] | 0 | 1 | 1 | CN_CHAR | 1
中
[e4 b8 ad]
0
1
1
CN_CHAR
1
华[e5 8d 8e]121CN_CHAR2 | 华 | [e5 8d 8e] | 1 | 2 | 1 | CN_CHAR | 2
华
[e5 8d 8e]
1
2
1
CN_CHAR
2
人[e4 ba ba]231CN_CHAR3 | 人 | [e4 ba ba] | 2 | 3 | 1 | CN_CHAR | 3
人
[e4 ba ba]
2
3
1
CN_CHAR
3
民[e6 b0 91]341CN_CHAR4 | 民 | [e6 b0 91] | 3 | 4 | 1 | CN_CHAR | 4
民
[e6 b0 91]
3
4
1
CN_CHAR
4
国 | 国
国

`

IKT | textraw_bytesstartendpositionLengthtypeposition | textraw_bytesstartendpositionLengthtypeposition | text | raw_bytes | start | end | positionLength | type | position | 中[e4 b8 ad]011CN_CHAR1 | 中[e4 b8 ad]011CN_CHAR1 | 中 | [e4 b8 ad] | 0 | 1 | 1 | CN_CHAR | 1 | 华[e5 8d 8e]121CN_CHAR2 | 华[e5 8d 8e]121CN_CHAR2 | 华 | [e5 8d 8e] | 1 | 2 | 1 | CN_CHAR | 2 | 人[e4 ba ba]231CN_CHAR3 | 人[e4 ba ba]231CN_CHAR3 | 人 | [e4 ba ba] | 2 | 3 | 1 | CN_CHAR | 3 | 民[e6 b0 91]341CN_CHAR4 | 民[e6 b0 91]341CN_CHAR4 | 民 | [e6 b0 91] | 3 | 4 | 1 | CN_CHAR | 4 | 国 | 国 | 国
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
textraw_bytesstartendpositionLengthtypeposition | text | raw_bytes | start | end | positionLength | type | position
text
raw_bytes
start
end
positionLength
type
position
中[e4 b8 ad]011CN_CHAR1 | 中 | [e4 b8 ad] | 0 | 1 | 1 | CN_CHAR | 1
中
[e4 b8 ad]
0
1
1
CN_CHAR
1
华[e5 8d 8e]121CN_CHAR2 | 华 | [e5 8d 8e] | 1 | 2 | 1 | CN_CHAR | 2
华
[e5 8d 8e]
1
2
1
CN_CHAR
2
人[e4 ba ba]231CN_CHAR3 | 人 | [e4 ba ba] | 2 | 3 | 1 | CN_CHAR | 3
人
[e4 ba ba]
2
3
1
CN_CHAR
3
民[e6 b0 91]341CN_CHAR4 | 民 | [e6 b0 91] | 3 | 4 | 1 | CN_CHAR | 4
民
[e6 b0 91]
3
4
1
CN_CHAR
4
国 | 国
国

`

不能截图，好尴尬了，没有分词，知道是那个配置导致的吗？我用其他版本的可以

**Comment by liang68** [comment]
应该是 ik 对应的 jar 包没有加载成功，路径可能出错

**Comment by inotgaoshou** [comment]
我再检查下，谢谢
